version: '3.3'
services:
  db:
    container_name: pg_project
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: german_pisarev
      POSTGRES_PASSWORD: Gurmanidze01
      POSTGRES_DB: education
    ports:
      - "5432:5432"
    network_mode: bridge

  education:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/education
      ENTRY_DELAY: 5
    ports:
      - "8080:8080"
    depends_on:
      - db
    network_mode: bridge
    links:
      - db